### ISSUE TITLE
Error in QGiS3:  'NoneType' object has no attribute 'selectedFeatures'

### ISSUE THREAD

**Issue by rogorido** [HeikkiVesanto/QGIS_Multi_Ring_Buffer#6]
Thanks for the plugin. I'm getting the following error with qgis3:

Traceback (most recent call last):
  File "/home/igor/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Multi_Ring_Buffer/multi_ring_buffer_dialog.py", line 86, in isSomethingSelected
    if not vlayer.selectedFeatures():
AttributeError: 'NoneType' object has no attribute 'selectedFeatures'

**Comment by HeikkiVesanto** [comment]
Thanks for the report. Will have a look.

**Comment by HeikkiVesanto** [comment]
Hi @rogorido 

I think I have fixed this. I have pushed a new version to the QGIS repo, it should be available soon. Version 1.1. Please update the plugin and try again.

Let me know if you still have the issue.

**Comment by rogorido** [comment]
thanks a lot. But I still get errors:
`
`
2018-03-19T16:20:38	WARNING	Traceback (most recent call last):
			  File "/home/igor/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Multi_Ring_Buffer/multi_ring_buffer_dialog.py", line 86, in isSomethingSelected
			    if not vlayer.selectedFeatures():
			AttributeError: 'NoneType' object has no attribute 'selectedFeatures'
			
2018-03-19T16:21:05	WARNING	Traceback (most recent call last):
			  File "/home/igor/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Multi_Ring_Buffer/multi_ring_buffer.py", line 358, in run
			    add_feat = self.dissolve(sel_feats)
			  File "/home/igor/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Multi_Ring_Buffer/multi_ring_buffer.py", line 212, in dissolve
			    self.iface.messageBar().pushWidget(progressMessageBar, self.iface.messageBar().INFO)
			AttributeError: 'QgsMessageBar' object has no attribute 'INFO'
`

**Comment by HeikkiVesanto** [comment]
Hi @rogorido 
That error is fixed as well in 1.1. It is still awaiting approval in the official repository.

You can clone this GitHub repository and replace the files in:

C:\Users\YOUR_USER_NAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Multi_Ring_Buffer

Or wait until approval. Usually takes about a day.

**Comment by rogorido** [comment]
yes, sorry. I reinstalled the previous version. I'll wait til tomorrow and I'll test it again. THanks again.

**Comment by HeikkiVesanto** [comment]
Version 1.1 is live in the official report now please upgrade and let me know if there are any further issues.

**Comment by rogorido** [comment]
Yes, it's working now. Thanks a lot again for the very useful plugin!
